version: '3.7'
services:
  mongodb:
    build: ./mongodb
    image: tms-messenger/mongo:latest
    container_name: tms-messenger-mongo
    # ports:
    #   - '27017:27017'
    # volumes:
    #   - ./mongodb/data:/data/db # 指定容器外部的数据存储位置
    # logging:
    #   driver: none

  redis:
    image: redis:alpine
    container_name: tms-messenger-redis
    # ports:
    #   - '6379:6379'

  back:
    build: ./back
    image: tms-messenger/back:latest
    container_name: tms-messenger-back
    # ports:
    #   - '3000:3000'
    # volumes:
    #   - ./fonts:/home/node/app/fonts # 指定字库文件存储位置
    # environment:
    #   - NODE_ENV=production
    #   - TMS_MESSENGER_MONGODB_HOST=mongodb
    #   - TMS_MESSENGER_MONGODB_PORT=27017
    #   - TMS_MESSENGER_MONGODB_DB=tms_messenger
    #   - TMS_MESSENGER_REDIS_HOST=redis
    #   - TMS_MESSENGER_REDIS_PORT=6379
    #   - TMS_MESSENGER_READ_MESSAGE_URL=
    #   - TMS_MESSENGER_MESSAGE_REQUEST_QUEUE_REDIS=master
    #   - TMS_MESSENGER_MESSAGE_REQUEST_QUEUE_NAME=tms_messenger_message_request
    #   - TMS_WXPROXY_MONGODB_DB=tms_messenger
    #   - TMS_WXPROXY_MONGODB_CL_CONFIG=channel
    #   - TMS_WXPROXY_MONGODB_CL_TEMPLATE_MESSAGE=request
    #   - TMS_KOA_JIMP_FONT_PATH=
    #   - TMS_KOA_JIMP_SAVE_FS_DOMAIN=output
    # command: ['./wait-for.sh', 'mongodb:27017', '-t', '300', '--', 'node', 'server']
