version: '3.7'
services:
  mongodb:
    build: ./mongodb
    image: tms-messenger/mongo:latest
    container_name: tms-messenger-mongo
    # ports:
    #   - '27017:27017'
    # volumes:
    #   - ./mongodb/data:/data/db # 指定容器外部的数据存储位置
    # logging:
    #   driver: none

  redis:
    image: redis:alpine
    container_name: tms-messenger-redis
    # ports:
    #   - '6379:6379'

  back:
    build: ./back
    image: tms-messenger/back:latest
    container_name: tms-messenger-back
    # ports:
    #   - '3000:3000'
    environment:
      - NODE_ENV=production
      - TMS_MESSENGER_MONGODB_HOST=mongodb
      - TMS_MESSENGER_MONGODB_PORT=27017
    command: ['./wait-for.sh', 'mongodb:27017', '-t', '300', '--', 'node', 'app']
