version: '3.7'
services:
  mmongodb:
    build: ./mongodb
    image: tms-msg/mongo:latest
    container_name: msg-mongo
  
  redis:
    build: ./redis
    image: tms-msg/redis:alpine
    container_name: msg-redis
  back:
    build: ./back
    image: tms-msg/back:latest
    container_name: msg-back
    environment:
       - TMS_APP_PORT=3000
       - TMS_APP_NAME=dev-op
       - TMS_APP_LOG4JS_LEVEL=debug
       - TMS_FINDER_FS_OUTDIR=/data/
       - TMS_FINDER_FS_ROOTDIR=/data/
       - TMS_MESSENGER_MONGODB_HOST=mmongodb
       - TMS_MESSENGER_MONGODB_PORT=27017
       - TMS_MESSENGER_MONGODB_DB=tms_messenger
       - TMS_MESSENGER_REDIS_HOST=redis
       - TMS_MESSENGER_REDIS_PORT=6379
    command: ['sh', './wait-for.sh', 'mmongodb:27017', '-t', '300', '--', 'node', 'server']
